# Generated by Django 4.2.6 on 2023-10-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Category',
            new_name='category',
        ),
    ]
